name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'    

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Add Source      
      run: dotnet nuget add source --username marcelobarbieri --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/marcelobarbieri/index.json"

    - name: Publish
      run: dotnet nuget push "bin/Release/*.nupkg" --api-key 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 --source https://nuget.pkg.github.com/marcelobarbieri/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
